opsdb/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^environment/$',views.envs,name='envs'),
    url(r'^environment/add_env/$',views.add_env,name='add_env'),
    url(r'^environment/edit_env/(\d+)/$',views.edit_env,name='edit_env'),
    url(r'^environment/delete/$',views.delete_env,name='delete_env'),
    url(r'^permission_rule/$',views.rules,name='rules'),
    url(r'^permission_rule/edit/(\d+)/$',views.edit_rule,name='edit_rule'),
    url(r'^hosts/$',views.hosts,name='hosts'),
    url(r'^host/(.+)/$',views.host,name='host'),
    url(r'^hosts/search/$',views.search_host,name='search_host'),
    url(r'^hosts/search_exact/$',views.search_exact_host,name='search_exact_host'),
    url(r'^hosts/add/$',views.add_host,name='add_host'),
    url(r'^hosts/add_batch/$',views.add_host_batch,name='add_host_batch'),
    url(r'^hosts/delete/(\d+)/$',views.delete_host,name='delete_host'),
    url(r'^hosts/delete_batch/$',views.delete_host_batch,name='delete_host_batch'),
    url(r'^hosts/edit/(\d+)/$',views.edit_host,name='edit_host'),
    url(r'^hosts/edit_batch/$',views.edit_host_batch,name='edit_host_batch'),
    url(r'^hostgroups/$',views.hostgroups,name='hostgroups'),
    url(r'^hostgroups/add/$',views.add_hostgroup,name='add_hostgroup'),
    url(r'^hostgroups/edit/(\d+)/$',views.edit_hostgroup,name='edit_hostgroup'),
    url(r'^hostgroups/delete/$',views.delete_hostgroup,name='delete_hostgroup'),
    url(r'^ops/cmd/$',views.cmd,name='cmd'),
    url(r'^ops/select_hosts/$',views.select_hosts,name='select_hosts'),
    url(r'^ops/search/$',views.search_host_for_cmd,name='search_host_for_cmd'),
    url(r'^ops/joblist/$',views.joblist,name='joblist'),
    url(r'^ops/job_cjid/(\d+)/$',views.job_cjid,name='job_cjid'),
    url(r'^ops/job_jid/(\d+)/$',views.job_jid,name='job_jid'),
    url(r'^ops/search_job/$',views.search_job,name='search_job'),
    url(r'^ops/cmds/$',views.cmds,name='cmds'),
    url(r'^ops/cmds/black/$',views.black_cmds,name='black_cmds'),
    url(r'^ops/cmds/add/$',views.add_cmd,name='add_cmd'),
    url(r'^ops/cmds/add_black/$',views.add_black_cmd,name='add_black_cmd'),
    url(r'^ops/cmds/edit/(\d+)/$',views.edit_cmd,name='edit_cmd'),
    url(r'^ops/cmds/delete/(\d+)/$',views.delete_cmd,name='delete_cmd'),
    url(r'^ops/cmds/delete/$',views.delete_cmds,name='delete_cmds'),
    url(r'^ops/save_cmd/$',views.save_cmd,name='save_cmd'),
    url(r'^ops/files/get/$',views.get_file,name='get_file'),
    url(r'^ops/files/put/$',views.put_file,name='put_file'),
    url(r'^ops/files/delete/(\d+)/$',views.delete_file,name='delete_file'),
    url(r'^ops/files/push/$',views.push_file,name='push_file'),
    url(r'^ops/scripts/$',views.scripts,name='scripts'),
    url(r'^ops/scripts/upload/$',views.upload_script,name='upload_script'),
    url(r'^ops/scripts/edit/(\d+)/$',views.edit_script,name='edit_script'),
    url(r'^ops/scripts/add/$',views.add_script,name='add_script'),
    url(r'^ops/scripts/copy/(\d+)/$',views.copy_script,name='copy_script'),
    url(r'^ops/scripts/delete/(\d+)/$',views.delete_script,name='delete_script'),
    url(r'^ops/scripts/exacute/(\d+)/$',views.exacute_script,name='exacute_script'),
    url(r'^ops/scripts/search/$',views.search_script,name='search_script'),
    url(r'^ops/states/$',views.states,name='states'),
    url(r'^ops/states/upload/$',views.upload_state,name='upload_state'),
    url(r'^ops/states/deploy/(\d+)/$',views.deploy_state,name='deploy_state'),
    url(r'^ops/states/delete/(\d+)/$',views.delete_state,name='delete_state'),
    url(r'^ops/cron/$',views.cron,name='cron'),
    url(r'^ops/cron/add/$',views.add_cron,name='add_cron'),
    url(r'^ops/cron/delete/(.+)/$',views.delete_cron,name='delete_cron'),
    url(r'^metrics/insert/$',views.metric_to_mongo,name='metric_to_mongo'),
    url(r'^metrics/show_host/(.+)/(.+)/$',views.show_host,name='show_host'),
    url(r'^metrics/show_performance/(.+)/(.+)/$',views.show_performance,name='show_performance'),
    url(r'^metrics/show_user/(.+)/(.+)/$',views.show_user,name='show_user'),
    url(r'^metrics/show_socket/(.+)/(.+)/$',views.show_socket,name='show_socket'),
    url(r'^metrics/show_process/(.+)/(.+)/$',views.show_process,name='show_process'),
    url(r'^zabbix/(.+)/(.+)/$',views.zabbix,name='zabbix'),
    url(r'^zabbix_refresh/$',views.zabbix_refresh,name='zabbix_refresh'),
]

xbox/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
from . import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$',views.base,name="base"),
    url(r'^blank/$',views.blank,name="blank"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),    
	url(r'^accounts/login',views.login,name="login"),
	url(r'^logout/',views.logout,name="logout"),
    url(r'^users/$',views.users,name="users"),
    url(r'^userprofile/(\d+)/$',views.userprofile,name="userprofile"),
    url(r'^changepasswd/$',views.changepasswd,name="changepasswd"),
    url(r'^add_user/$',views.add_user,name='add_user'),
    url(r'^edit_user/(\d+)/$',views.edit_user,name='edit_user'),
    url(r'^disable_user/$',views.disable_user,name='disable_user'),
    url(r'^enable_user/$',views.enable_user,name='enable_user'),
    url(r'^delete_user/$',views.delete_user,name='delete_user'),
    url(r'^reset_password/$',views.resetpwd,name='resetpwd'),
    url(r'^groups/$',views.groups,name='groups'),
    url(r'^group_has_users/(\d+)/$',views.group_has_users,name='group_has_users'),
    url(r'^add_group/$',views.add_group,name='add_group'),
    url(r'^edit_group/(\d+)/$',views.edit_group,name='edit_group'),
    url(r'^delete_group/$',views.delete_group,name='delete_group'),
    url(r'^audit/',include('audit.urls',namespace='audit')),
    url(r'^opsdb/',include('opsdb.urls',namespace='opsdb')),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^installation/', include('installation.urls',namespace='installation')),
]

opsdb/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from xbox.decorators import role_required,black_command_check
from xbox.paginator import my_paginator
from django.views.decorators.csrf import csrf_exempt
from .models import *
from xbox.settings import FTP_IP,FTP_PORT
from xbox.settings import SALT_MASTER_HOSTNAME,SALT_IP,SALT_PORT,SALT_USER,SALT_PASSWD,SALT_FILE_ROOTS,SALT_SCRIPTS,SALT_STATES,SALT_FILE_DOWNLOADS
from xbox.settings import MONGO_CLIENT
from xbox.settings import scheduler
from opsdb.saltapi import SaltAPI
from xbox.sshapi import remote_cmd
from json2html import *
from django.db.models import Q
import time,datetime
from .utils import exacute_cmd,upload_file,push_file_to_minion,get_file_from_minion,run_script,state_deploy
import os
import collections
import json
from collections import OrderedDict
from pyecharts import Line,Grid,Page
from pyecharts.constants import DEFAULT_HOST
from .zabbix_utils import *
import pprint
# Create your views here.

@login_required
@role_required('admin')
def envs(request):
	env_list = Environment.objects.all()
	page_number =  request.GET.get('page_number')
	page = request.GET.get('page')
	paginator,envs,page_number = my_paginator(env_list,page,page_number)
	return render(request,'opsdb/env/envs.html',locals())

@login_required
@role_required('admin')
def add_env(request):
	if request.method == "GET":
		return render(request, 'opsdb/env/add_env.html',locals())
	else:
		name = request.POST.get('name','')
		comment = request.POST.get('comment','')
		try:
			Environment.objects.update_or_create(name=name,defaults={'comment':comment})
			messages.success(request, '添加成功')
		except Exception as e:
			messages.error(request, e)
		return redirect('opsdb:envs')

@login_required
@role_required('admin')
def edit_env(request,id):
	env = Environment.objects.get(pk=id)
	if request.method == "GET":
		return render(request, 'opsdb/env/edit_env.html',locals())
	else:
		name = request.POST.get('name','')
		comment = request.POST.get('comment','')
		try:
			Environment.objects.update_or_create(name=name,defaults={'comment':comment})
			messages.success(request, '环境更新成功')
		except Exception as e:
			messages.error(request, e)
		return redirect('opsdb:envs')

@login_required
@role_required('admin')
@csrf_exempt
def delete_env(request):
	ids = request.POST.getlist('ids[]','')
	ret = 'success'
	try:
		Environment.objects.filter(pk__in=ids).delete()
	except Exception as e:
		ret = str(e)
	return HttpResponse(ret)

@login_required
@role_required('admin')
def rules(request):
	rule_list = Rule.objects.all()
	page_number =  request.GET.get('page_number')
	page = request.GET.get('page')
	paginator,rules,page_number = my_paginator(rule_list,page,page_number)
	return render(request,'opsdb/rule/rules.html',locals())

@login_required
@role_required('admin')
@csrf_exempt
def edit_rule(request,id):
	hostgroups = HostGroup.objects.all()
	rule = Rule.objects.get(pk=id)
	if request.method == "GET":
		return render(request, 'opsdb/rule/edit_rule.html',locals())
	else:
		try:
			hostgroup_list = request.POST.getlist('hostgroups','')
			comment = request.POST.get('comment','')
			rule.hostgroups = hostgroup_list
			rule.created_by = request.user
			rule.comment = comment
			rule.save()
			messages.success(request, '规则更新成功')
		except Exception as e:
			messages.error(request, e)
		return redirect('opsdb:rules')

@login_required
@role_required('hostadmin')
@csrf_exempt
def add_host(request):
	if request.method == "GET":
		hostgroups = HostGroup.objects.all()
		envs = Environment.objects.all()
		return render(request,'opsdb/host/add_host.html',locals())
	else:
		ip = request.POST.get('ip','')
		port = request.POST.get('port','')
		user = request.POST.get('username','')
		passwd = request.POST.get('password','')
		salt = request.POST.get('salt','')
		zabbix = request.POST.get('zabbix','')
		hostgroups = request.POST.getlist('hostgroups','')
		env = request.POST.get('env','')
		cmd = "curl -s http://%s:%s/install-minion.sh | sh 2>&1"%(FTP_IP,FTP_PORT)
		ret = remote_cmd(cmd,ip,port=int(port),user=user,passwd=passwd)
		if ret['status'] and not ret['err']:
			host,created = Host.objects.get_or_create(ip=ip)
			if host:
				if hostgroups:
					host.hostgroups = hostgroups
				if env:
					host.environment = Environment.objects.get(pk=env)
					host.save()
			messages.success(request, '添加成功')
			return redirect('opsdb:hosts')
		else:
			messages.error(request, ret['err'])
			return render(request,'opsdb/host/add_host.html',locals())

@login_required
@role_required('hostadmin')
@csrf_exempt
def add_host_batch(request):
	if request.method == "GET":
		hostinfo = '''#请按照实例格式编辑主机信息:
﻿﻿#IP地址           SSH端口     SSH用户    SSH密码(仅用于安装客户端，不保存)
192.168.1.1     22                root           12345678
192.168.1.2     22                root           87654321'''
		return render(request,'opsdb/host/add_host_batch.html',locals())
	else:
		hostinfo = request.POST.get('hostinfo','')
		lines = hostinfo.split('\n')
		result = {}
		for line in lines:
			host = line.split()
			ip,port,user,passwd = host[0],host[1],host[2],host[3]
			cmd = "curl -s http://%s:%s/install-minion.sh | sh 2>&1"%(FTP_IP,FTP_PORT)
			ret = remote_cmd(cmd,ip,port=int(port),user=user,passwd=passwd,timeout=10)
			if ret['status'] and not ret['err']:
				host,created = Host.objects.get_or_create(ip=ip)
				if host:
					result[ip] = {'status':'Success','comment':'添加成功'}
			else:
				result[ip] = {'status':'Fail','comment':ret['err']}
				continue
		result = json2html.convert(json = result)
		return render(request,'opsdb/host/add_host_batch.html',locals())

@login_required
@role_required('hostadmin')
def hosts(request):
	if request.user.is_superuser:
		host_list = Host.objects.select_related().all()
	else:
		if request.user.groups:
			host_list = []
			for group in request.user.groups.all():
				for hostgroup in group.rule.hostgroups.all():
					host_list.extend(hostgroup.host_set.all())
	page_number =  request.GET.get('page_number')
	page = request.GET.get('page')
	paginator,hosts,page_number = my_paginator(host_list,page,page_number)
	return render(request,'opsdb/host/hosts.html',locals())

def host(request,id):
	minion_id = id
	hosts = MONGO_CLIENT.salt.salt_grains.find({'id':id}).sort([("_id", -1)]).limit(1)
	# grains = {'os':{},'software':{},'users':{},'hardware':{},'cron':{}}
	if hosts:
		for host in hosts:
			ret = host.get('return',None)
			os_family = ret.get('os_family',None)
			factor = {}
			if os_family == 'Windows':
				summary = json2html.convert(json = ret)
				factor['ip'] = ret.get('ipv4',None)
			else:
				os_family = "Linux"
				# operation system info
				# grains = {'os':{},'software':{},'users':{},'hardware':{},'cron':{}}
				# grains['os']['fqdn'] = ret.get('fqdn',None)
				# grains['os']['os'] = ' '.join([ret.get('os',None),ret.get('osrelease',None)])
				# grains['os']['kernel'] = ' '.join([ret.get('kernel',None),ret.get('kernelrelease',None)])
				# grains['os']['disk-usage'] = ret.get('disk-usage',None)
				# grains['os']['selinux'] = ret.get('selinux',None)
				# grains['os']['fqdn_ip4'] = ret.get('fqdn_ip4',None)
				# grains['os']['ip4_interfaces'] = ret.get('ip4_interfaces',None)
				# grains['os']['ip6_interfaces'] = ret.get('ip6_interfaces',None)
				# grains['os']['routes'] = ret.get('routes',None)
				# grains['os']['dns'] = ret.get('dns',None)
				# grains['os']['ntp'] = ret.get('ntp',None)
				# grains['os']['iptable'] = ret.get('iptable',None)
				# grains['os']['systemd'] = ret.get('systemd',None)
				# grains['os']['lsb_distrib'] = {'id':ret['lsb_distrib_id'],'codename':ret['lsb_distrib_codename']}
				# os = json2html.convert(json = grains['os'])

				# software info
				# grains['software'] = ret.get('software',None)
				# users = json2html.convert(json = grains['software'])

				# system user info
				# grains['users'] = ret.get('users',None)
				# users = json2html.convert(json = grains['users'])

				# hardware info
				# grains['hardware']['virtual'] = ret.get('virtual',None)
				# grains['hardware']['serialnumber'] = ret.get('serialnumber',None)
				# grains['hardware']['cpu'] = ' * '.join([str(ret.get('num_cpus')),ret.get('cpu_model')])
				# grains['hardware']['mem_total(G)'] = ("%.2f"%(ret.get('mem_total',0)/1024.0))
				# grains['hardware']['Hugepage & Swap'] = ret.get('Hugepage & Swap',None)
				# grains['hardware']['HBA'] = ret.get('HBA',None)
				# hardware = json2html.convert(json = grains['hardware'])

				# user cron info
				# cron = json2html.convert(json = grains['cron'])

				# grains = {'os':{},'software':{},'users':{},'hardware':{},'cron':{}}
				factor['hostname'] = ret.get('nodename',None)
				factor['os'] = ' '.join([ret.get('os',None),ret.get('osrelease',None)])
				factor['kernel'] = ' '.join([ret.get('kernel',None),ret.get('kernelrelease',None)])
				factor['disk-usage'] = ret.get('disk-usage',None)
				factor['selinux'] = ret.get('selinux',None)
				factor['ip'] = ret.get('ipv4',None)
				factor['ip4_interfaces'] = ret.get('ip4_interfaces',None)
				factor['ip6_interfaces'] = ret.get('ip6_interfaces',None)
				factor['routes'] = ret.get('routes',None)
				factor['dns'] = ret.get('dns',None)
				factor['ntp'] = ret.get('ntp',None)
				factor['iptable'] = ret.get('iptable',None)
				factor['virtual'] = ret.get('virtual',None)
				factor['serialnumber'] = ret.get('serialnumber',None)
				factor['cpu'] = ' * '.join([str(ret.get('num_cpus')),ret.get('cpu_model')])
				factor['mem_total(G)'] = ("%.2f"%(ret.get('mem_total',0)/1024.0))
				factor['Hugepage & Swap'] = ret.get('Hugepage & Swap',None)

				order_summary = OrderedDict(
			 [('ip',factor['ip']),('hostname',factor['hostname']),('virtual',factor['virtual']),\

opsdb/templates/opsdb/ops/scripts.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="{%static 'img/favicon.ico'%}">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-reset.css'%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'assets/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet">
    <link href="{%static 'css/style-responsive.css'%}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{%static 'js/html5shiv.js'%}"></script>
      <script src="{%static 'js/respond.min.js'%}"></script>
    <![endif]-->
  </head>

  <body>

    <section class="wrapper site-min-height">
        <!-- page start-->
        <div class="row">
          <div class="col-lg-12">
              <!--breadcrumbs start -->
              <ul class="breadcrumb">
                  <li><a href="#"></i>运维平台</a></li>
                  <li class="active">脚本管理</li>
              </ul>
              <!--breadcrumbs end -->
          </div>
        </div>

         <div class="row">
        <div class="col-lg-12" id="message">
             {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-block alert-danger fade in">
                            <button data-dismiss="alert" class="close close-sm" type="button">
                                <i class="icon-remove"></i>
                            </button>
                            <strong>Error !</strong> {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-success fade in">
                            <button data-dismiss="alert" class="close close-sm" type="button">
                                <i class="icon-remove"></i>
                            </button>
                            <strong>Success !</strong> {{ message }}
                        </div>
                    {% endif %}                  
                {% endfor %}
              {% endif %}
        </div>
      </div>
        
        <section class="panel">
          <header class="panel-heading tab-bg-dark-navy-blue ">
              <ul class="nav nav-tabs">
                  <li class="active">
                      <a href="{% url 'opsdb:scripts' %}" style="left: 15px;">脚本管理</a>
                  </li>
              </ul>
          </header>
          {% block content %}
          <div class="panel-body">
              <div class="tab-content">
                  <div class="tab-pane active">
                        <div class="mail-option">
                               <div class="btn-group">
                                  <button type="button" class="btn label label-inverse" onclick="window.location.reload()"><i class="icon-refresh"></i> 刷新</button>
                               </div>
                                <div class="btn-group">
                                   <a onclick="upload_script()"><button type="button" class="btn label label-inverse"><i class="icon-cloud-upload"></i> 上传脚本</button></a>
                               </div>
                               <div class="btn-group">
                                   <a href="{% url 'opsdb:add_script' %}"><button type="button" class="btn label label-inverse"><i class="icon-plus"></i> 新建脚本</button></a>
                               </div>
                                 
                                  <div class="btn-group">
                                    <form action="{% url 'opsdb:search_script' %}" method="post">
                                      {% csrf_token %}
                                      <input type="text" class="form-control search" placeholder="模糊查询" name="keyword">
                                    </form>
                                  </div>

                               <ul class="unstyled inbox-pagination">
                                   <li>
                                    <span class="pages">合计:{{ paginator.count }}&nbsp</span>
                                    <span class="per-page">每页:</span>
                                    <select class="dropdown-select" name="page_number" onchange="javascript:window.location.href='?page_number='+ this.value;">
                                       <option value="{{page_number}}">{{page_number}}</option>
                                       <option value="10">10</option>
                                       <option value="20">20</option>
                                       <option value="50">50</option>
                                       <option value="100">100</option>
                                       <option value="10000">10000</option>
                                    </select>
                                   </li>

                                   <li>
                                     <span>&nbsp&nbsp{{ scripts.number }} / {{ scripts.paginator.num_pages }}</span>
                                   </li>
                                   
                                   <li>
                                       {% if scripts.has_previous %}
                                       <a href="?page={{ scripts.previous_page_number }}" class="np-btn"><i class="icon-angle-left  pagination-left"></i></a>
                                       {% endif %}
                                   </li>
                                   <li>
                                       {% if scripts.has_next %}
                                       <a href="?page={{ scripts.next_page_number }}" class="np-btn"><i class="icon-angle-right pagination-right"></i></a>
                                       {% endif %}
                                   </li>
                               </ul>
                        </div>
                        <table class="table table-inbox table-hover" border="5" id='mytable'>
                          <thead>
                                  <tr>
                                    <!-- <th style="width: 37px;"><input type="checkbox" name="all" id="all"></th> -->
                                    <th><small>脚本别名</small></th>
                                    <th><small>脚本名</small></th>
                                    <th><small>创建者</small></th>
                                    <th><small>Last_updated_by</small></th>
                                    <th><small>更新时间</small></th>
                                    <th><small>操作</small></th>
                                  </tr>
                            </thead>
                              <tbody>
                                {% for script in scripts %}
                                  <tr>
                                    <!-- <td><input type="checkbox"></td> -->
                                    <td id="{{script.id}}"><small>{{script.name}}</small></td>
                                    <td><small>{{script.script_name}}</small></td>
                                    <td><small>{{script.created_by}}</small></td>
                                    <th><small>{{script.comment}}</small></th>
                                    <td><small>{{script.update_time | date:'Y-m-d H:m:s' }}</small></td>
                                    <td style="width: 126px;">
                                      <small>
                                        <button class="btn btn-info btn-xs" ><a href="{% url 'opsdb:exacute_script' script.id %}" data-placement="left" data-toggle="tooltip" class="tooltips" data-original-title="执行脚本"><i class="icon-play"></i></a></button>
                                        <button class="btn btn-primary btn-xs"><a href="{% url 'opsdb:edit_script' script.id %}" data-placement="left" data-toggle="tooltip" class="tooltips" data-original-title="编辑脚本"><i class="icon-pencil"></i></a></button>
                                        <button class="btn btn-default btn-xs"><a href="{% url 'opsdb:copy_script' script.id %}" data-placement="left" data-toggle="tooltip" class="tooltips" data-original-title="复制脚本"><i class="icon-paste"></i></a></button>
                                        <button class="btn btn-danger btn-xs"><a href="{% url 'opsdb:delete_script' script.id %}" data-placement="left" data-toggle="tooltip" class="tooltips" data-original-title="删除脚本"><i class="icon-trash"></i></a></button>
                                      </small>
                                    </td>
                                    </tr>
                                {% endfor %}
                              </tbody>
                        </table>
                      </div>
              </div>
          </div>
          {% endblock %}
        </section>
        <!-- page end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script class="include" type="text/javascript" src="{%static 'js/jquery.dcjqaccordion.2.7.js'%}"></script>
    <script src="{%static 'js/jquery.scrollTo.min.js'%}"></script>
    <script src="{%static 'js/jquery.nicescroll.js'%}" type="text/javascript"></script>
    <script src="{%static 'js/respond.min.js'%}" ></script>

    <!--common script for all pages-->
    <script src="{%static 'js/common-scripts.js'%}"></script>
    <script src="{%static 'layer/layer.js'%}"></script>

    <script type="text/javascript">
        $(function() {
          var all_checked = false;
          $(":checkbox").click(function() {
              var table = $(this).parents("table");
              if($(this).attr("id") === "all") {
                  table.find(":checkbox").prop("checked", !all_checked);
                  all_checked = !all_checked;
              }
              else {
                  table.find(":checkbox[id!=all]").each(function (i) {
                      if(!$(this).is(":checked")) {
                          table.find("#all").prop("checked", false);
                          all_checked = false;
                          return false;
                      }
                      $("#all").prop("checked", true);
                      all_checked = true;
                  });
              }
          });
      });

      function get_server_id(){
        var tbodyObj = document.getElementById('mytable');
        var ids = [];
            $("table :checkbox").each(function(key,value){
                if($(value).prop('checked')){
                    if (value.id == 'all') return true
                    ids.push(tbodyObj.rows[key].cells[1].id);
                }
            });
            return ids
      }

      function upload_script(){
         var index = layer.open({
            type: 2,
            shift: 1,
            title: '上传脚本至文件服务器',
            area : ['60%','50%'],
            content: "{% url 'opsdb:upload_script' %}",
            end: function() {
                  window.location.reload();
                }
          });
      }

      function delete_script_batch() {
        var ids = get_server_id();
        if (ids.length ==0 )
        {
          layer.alert("请至请先选中主机");
        }
        else
        {   
            layer.confirm('请确认是否要删除', function(index){
                  $.post("",{'ids':ids},function(data){
                    layer.close(index);
                    if (data == 'success')
                    {
                      document.getElementById('message').innerHTML='<div class="alert alert-success fade in"> <button data-dismiss="alert" class="close close-sm" type="button"> <i class="icon-remove"></i> </button> <strong>Success !</strong> 删除成功</div>';
                      setTimeout("window.location.reload()", 2000);
                    }
                    else
                    {
                      document.getElementById('message').innerHTML='<div class="alert alert-block alert-danger fade in"> <button data-dismiss="alert" class="close close-sm" type="button"> <i class="icon-remove"></i> </button> <strong>Error !</strong>' + data + '</div>';
                    }
                  });
                      
            }); 
        }
      }

    </script>
  </body>
</html>