installation/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from . import views

urlpatterns = [
    url(r'^post_server_info/',views.post_server_info,name='post_server_info'),
    url(r'^servers/init/',views.init,name='init'),
    url(r'^servers/install/',views.install,name='install'),
    url(r'^server/detail/(\w+)/$',views.server_detail,name='server_detail'),
    url(r'^server/delete/$',views.server_delete,name='server_delete'),
    url(r'^server/edit/(\w+)/$',views.server_edit,name='server_edit'),
    url(r'^server/raid/(\w+)/(\w+)/(\w*)',views.server_raid,name='server_raid'),
    url(r'^server/confirm_to_prod/(\w+)/$',views.confirm_to_prod,name='confirm_to_prod'),
    url(r'^select_cab/',views.select_cab,name='select_cab'),
    url(r'^server/status/',views.server_change_status,name='server_change_status'),
    url(r'^server/power/$',views.server_power,name='server_power'),
    url(r'^ipmi/update/(\w+)/$',views.update_ipmi,name='update_ipmi'),
    url(r'^install_pre_post/$',views.install_pre_post,name='install_pre_post'),
    url(r'^server/install/(\w+)/$',views.get_system,name='get_system'),
    url(r'^server/add_system/(\w+)/$',views.add_system,name='add_system'),
    url(r'^server/edit_system/(\w+)/(\w+)/$',views.edit_system,name='edit_system'),
    url(r'^server/system/view/(\w+)/$',views.view_system,name='view_system'),
    url(r'^server/system/delete/(\w+)/(\w+)/$',views.delete_system,name='delete_system'),
    url(r'^vm/vcenter/$',views.vcenter,name='vcenter'),
    url(r'^vm/add_vcenter/$',views.add_vcenter,name='add_vcenter'),
    url(r'^vm/edit_vcenter/(\d+)/$',views.edit_vcenter,name='edit_vcenter'),
    url(r'^vm/delete_vcenter/(\d+)/$',views.delete_vcenter,name='delete_vcenter'),
    url(r'^vm/add_vm/$',views.add_vm,name='add_vm'),
    url(r'^vm/get_obj',views.get_obj,name='get_obj'),
    url(r'^installserver/$',views.cobbler,name='cobbler'),
    url(r'^installserver/add/$',views.add_cobbler,name='add_cobbler'),
    url(r'^installserver/edit/(\d+)/$',views.edit_cobbler,name='edit_cobbler'),
]

xbox/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
from . import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$',views.base,name="base"),
    url(r'^blank/$',views.blank,name="blank"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),    
	url(r'^accounts/login',views.login,name="login"),
	url(r'^logout/',views.logout,name="logout"),
    url(r'^users/$',views.users,name="users"),
    url(r'^userprofile/(\d+)/$',views.userprofile,name="userprofile"),
    url(r'^changepasswd/$',views.changepasswd,name="changepasswd"),
    url(r'^add_user/$',views.add_user,name='add_user'),
    url(r'^edit_user/(\d+)/$',views.edit_user,name='edit_user'),
    url(r'^disable_user/$',views.disable_user,name='disable_user'),
    url(r'^enable_user/$',views.enable_user,name='enable_user'),
    url(r'^delete_user/$',views.delete_user,name='delete_user'),
    url(r'^reset_password/$',views.resetpwd,name='resetpwd'),
    url(r'^groups/$',views.groups,name='groups'),
    url(r'^group_has_users/(\d+)/$',views.group_has_users,name='group_has_users'),
    url(r'^add_group/$',views.add_group,name='add_group'),
    url(r'^edit_group/(\d+)/$',views.edit_group,name='edit_group'),
    url(r'^delete_group/$',views.delete_group,name='delete_group'),
    url(r'^audit/',include('audit.urls',namespace='audit')),
    url(r'^opsdb/',include('opsdb.urls',namespace='opsdb')),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^installation/', include('installation.urls',namespace='installation')),
]

installation/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from opsdb.models import Cabinet,Contacter

class ServerStatus(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="server_status_id")
    status_type        = models.CharField(max_length=50,blank=True,null=True,db_column="server_status_type")
    name               = models.CharField(max_length=100,blank=True,null=True,db_column="server_status_name")
    class Meta:
        db_table = 'server_status'

    def __unicode__(self):
        return self.status_type

class Tag(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="tag_id")
    tag_type           = models.CharField(max_length=10,blank=True,null=True)
    description        = models.CharField(max_length=30,blank=True,null=True)

    class Meta:
        db_table = 'tag'

    def __unicode__(self):
        return self.tag_type           

class Server(models.Model):
    id                 = models.CharField(max_length=100,primary_key=True,db_column="server_id")
    sn                 = models.CharField(max_length=100,blank=True,null=True)
    cpu_model          = models.CharField(max_length=100,blank=True,null=True)
    cpu_sockets        = models.IntegerField(blank=True,null=True)
    cpu_cores          = models.IntegerField(blank=True,null=True)
    cpu_threads        = models.IntegerField(blank=True,null=True)
    mem_size           = models.IntegerField(blank=True,null=True)
    mem_total_slots    = models.IntegerField(blank=True,null=True)
    mem_free_slots     = models.IntegerField(blank=True,null=True)
    raid_adapter       = models.CharField(max_length=200,blank=True,null=True)
    raid_adapter_slot  = models.CharField(max_length=20,blank=True,null=True)
    cabinet            = models.ForeignKey(Cabinet,blank=True, null=True,on_delete=models.PROTECT)
    serverstatus       = models.ForeignKey(ServerStatus,blank=True, null=True,on_delete=models.PROTECT)
    ipmi_ip            = models.GenericIPAddressField(blank=True,null=True)
    ipmi_user          = models.CharField(max_length=30,blank=True,null=True)
    ipmi_pass          = models.CharField(max_length=30,blank=True,null=True)
    tag                = models.ForeignKey(Tag,blank=True, null=True,on_delete=models.PROTECT)
    unit               = models.IntegerField(blank=True,null=True)
    contacter          = models.ForeignKey(Contacter,blank=True, null=True,on_delete=models.PROTECT)
    pxe_mac            = models.CharField(max_length=30,blank=True,null=True)
    pxe_ip             = models.GenericIPAddressField(blank=True,null=True)
    vendor             = models.CharField(max_length=30,blank=True,null=True)
    model              = models.CharField(max_length=30,blank=True,null=True)
    prod_ip            = models.GenericIPAddressField(blank=True,null=True)
    power              = models.CharField(max_length=10,blank=True,null=True,default='on')
    create_time        = models.DateTimeField(auto_now_add=True)
    update_time        = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'server'
        ordering = ['-create_time']

    def __unicode__(self):
        return self.id

class Disk(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="disk_id")
    path               = models.CharField(max_length=30,blank=True,null=True,db_column="disk_name")
    dtype              = models.CharField(max_length=30,blank=True,null=True,db_column="disk_model")
    server             = models.ForeignKey(Server)
    raid_name          = models.CharField(max_length=100,blank=True,null=True)
    raid_type          = models.CharField(max_length=100,blank=True,null=True)
    size               = models.CharField(max_length=30,blank=True,null=True,db_column="disk_size")

    class Meta:
        db_table = 'disk'

    def __unicode__(self):
        return self.path

class Nic(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="nic_id")
    name               = models.CharField(max_length=20,blank=True,null=True,db_column="nic_name")
    mac                = models.CharField(max_length=50,blank=True,null=True,db_column="mac")
    model              = models.CharField(max_length=100,blank=True,null=True,db_column="nic_model")
    server             = models.ForeignKey(Server)

    class Meta:
        db_table = 'nic'
    
    def __unicode__(self):
        return self.mac

class PreSystem(models.Model):
    ip                 = models.GenericIPAddressField(blank=True,null=True,unique=True)
    name               = models.CharField(max_length=50,blank=True,null=True)
    hostname           = models.CharField(max_length=50,blank=True,null=True)
    mac                = models.CharField(max_length=50,blank=True,null=True)
    profile            = models.CharField(max_length=50,blank=True,null=True)
    progress           = models.IntegerField(blank=True,null=True,default=-1)
    server             = models.OneToOneField(Server)
    create_time        = models.DateTimeField(auto_now_add=True)
    update_time        = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'pre_system'
        ordering = ['-create_time']
    
    def __unicode__(self):
        return self.profile

class Vcenter(models.Model):
    name               = models.CharField(max_length=50,blank=True,null=True)
    ip                 = models.GenericIPAddressField(blank=True,null=True,unique=True)
    port               = models.CharField(max_length=10,default='443')
    user               = models.CharField(max_length=50,blank=True,null=True)
    password           = models.CharField(max_length=50,blank=True,null=True)

    class Meta:
        db_table = 'vcenter'
    
    def __unicode__(self):
        return self.name

class Datastore(models.Model):
    name               = models.CharField(max_length=50,blank=True,null=True)
    capacity           = models.CharField(max_length=50,blank=True,null=True)
    free_space         = models.CharField(max_length=50,blank=True,null=True)
    provisioned        = models.CharField(max_length=50,blank=True,null=True)
    uncommitted        = models.CharField(max_length=50,blank=True,null=True)
    hosts              = models.IntegerField(blank=True,null=True,default=0)
    vms                = models.IntegerField(blank=True,null=True,default=0)
    vcenter            = models.ForeignKey(Vcenter,blank=True, null=True)

    class Meta:
        db_table = 'vm_datastore'
    
    def __unicode__(self):
        return self.name

class Datacenter(models.Model):
    name               = models.CharField(max_length=50,blank=True,null=True)
    vcenter            = models.ForeignKey(Vcenter,blank=True,null=True)

    class Meta:
        db_table = 'vm_datacenter'
    
    def __unicode__(self):
        return self.name
          
class Cluster(models.Model):
    name               = models.CharField(max_length=50,blank=True,null=True)
    datacenter         = models.ForeignKey(Datacenter,blank=True, null=True)

    class Meta:
        db_table = 'vm_cluster'
    
    def __unicode__(self):
        return self.name

class VmHost(models.Model):
    ip                 = models.GenericIPAddressField(blank=True,null=True,unique=True)    
    cluster            = models.ForeignKey(Cluster,blank=True, null=True)
    server             = models.OneToOneField(Server,blank=True, null=True)

    class Meta:
        db_table = 'vm_host'
    
    def __unicode__(self):
        return self.ip

class Guest(models.Model):
    name               = models.CharField(max_length=50,blank=True,null=True)
    annotation         = models.CharField(max_length=200,blank=True,null=True)
    cpu                = models.IntegerField(blank=True,null=True,default=0)
    diskGB             = models.CharField(max_length=50,blank=True,null=True)
    folder             = models.CharField(max_length=50,blank=True,null=True)
    mem                = models.IntegerField(blank=True,null=True,default=0)
    ostype             = models.CharField(max_length=50,blank=True,null=True)
    path               = models.CharField(max_length=50,blank=True,null=True)
    status             = models.CharField(max_length=50,blank=True,null=True)
    is_template        = models.BooleanField(default=False)
    host               = models.ForeignKey(VmHost,blank=True, null=True)
    datastore          = models.ForeignKey(Datastore,blank=True, null=True)

    class Meta:
        db_table = 'vm_guest'
    
    def __unicode__(self):
        return self.name

class Vnet(models.Model):
    mac                = models.CharField(max_length=50,primary_key=True)
    connected          = models.CharField(max_length=50,blank=True,null=True)
    ip                 = models.GenericIPAddressField(blank=True,null=True,unique=True)
    netlabel           = models.CharField(max_length=100,blank=True,null=True)
    prefix             = models.CharField(max_length=50,blank=True,null=True)   
    guest              = models.ForeignKey(Guest,blank=True, null=True)

    class Meta:
        db_table = 'vm_guest_net'
    
    def __unicode__(self):
        return self.mac

class Cobbler(models.Model):
    ip                 = models.GenericIPAddressField(blank=True,null=True,unique=True)
    port               = models.IntegerField(blank=True,null=True,default=80)
    user               = models.CharField(max_length=50,blank=True,null=True)
    password           = models.CharField(max_length=50,blank=True,null=True)

    class Meta:
        db_table = 'cobbler'
    
    def __unicode__(self):
        return self.ip

installation/templates/installation/ph/confirm_to_prod.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="{%static 'img/favicon.ico'%}">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-reset.css'%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'assets/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />

    <link rel="stylesheet" href="{%static 'assets/bootstrap-fileupload/bootstrap-fileupload.css'%}" />
    <link rel="stylesheet" href="{%static 'assets/bootstrap-datepicker/css/datepicker.css'%}" />
    <link rel="stylesheet" href="{%static 'assets/bootstrap-timepicker/compiled/timepicker.css'%}" />
    <link rel="stylesheet" href="{%static 'assets/bootstrap-colorpicker/css/colorpicker.css'%}" />
    <link rel="stylesheet" href="{%static 'assets/bootstrap-daterangepicker/daterangepicker-bs3.css'%}" />
    <link rel="stylesheet" href="{%static 'assets/bootstrap-datetimepicker/css/datetimepicker.css'%}" />
    <link rel="stylesheet" href="{%static 'assets/bootstrap-wysihtml5/bootstrap-wysihtml5.css'%}" />
    <link rel="stylesheet" href="{%static 'assets/jquery-multi-select/css/multi-select.css'%}" />
    <!-- Custom styles for this template -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet">
    <link href="{%static 'css/style-responsive.css'%}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{%static 'js/html5shiv.js'%}"></script>
      <script src="{%static 'js/respond.min.js'%}"></script>
    <![endif]-->
  </head>

  <body>

    <section class="wrapper site-min-height">
      <!-- page start-->
      <div class="row">
        <div class="col-lg-12">
            <!--breadcrumbs start -->
              <ul class="breadcrumb">
                  <li><a href="#"></i>部署平台</a></li>
                  <li><a href="{% url 'installation:install' %}">物理机安装</a></li>
                  <li class="active">确认上线</li>
              </ul>
            <!--breadcrumbs end -->
        </div>
      </div>

            <div class="row">
        <div class="col-lg-12" id="message">
             {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-block alert-danger fade in">
                            <button data-dismiss="alert" class="close close-sm" type="button">
                                <i class="icon-remove"></i>
                            </button>
                            <strong>Error !</strong> {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-success fade in">
                            <button data-dismiss="alert" class="close close-sm" type="button">
                                <i class="icon-remove"></i>
                            </button>
                            <strong>Success !</strong> {{ message }}
                        </div>
                    {% endif %}                  
                {% endfor %}
              {% endif %}
        </div>
      </div>
	      <div class="row">
                <div class="col-md-12">
                  <section class="panel">
                      <div class="panel-body">
                          <form class="form-horizontal" role="form" action="{% url 'installation:confirm_to_prod' server.id %}" method="post" role="form" id='confirm_to_prod'>
                              {% csrf_token %}     
                            <div class="form-group">
                              <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">ID </span></label>
                              <div class="col-xs-8 col-md-6 col-sm-6" >
                                    <input class="form-control" name="id" type="text" value="{{server.id}}" readonly="readonly">
                              </div>
                            </div>

                            <div class="form-group">
                              <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">IP(上线地址）*</span></label>
                              <div class="col-xs-8 col-md-6 col-sm-6" >
                                    <input class="form-control" name="ip" required="required" type="text" value="{{server.presystem.ip}}">
                              </div>
                            </div>

                            <div class="form-group" >
                              <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">操作系统 </span></label>
                              <div class="col-xs-8 col-md-6 col-sm-6" >
                                <input class="form-control" name="os" required="required" type="text" value="{{server.presystem.profile}}" readonly="readonly">
                              </div>
                            </div>

                    		    <div class="form-group">
                              <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">环境 </span></label>
                              <div class="col-xs-8 col-md-6 col-sm-6" >
                                      <select class="form-control m-bot15" name="env">
                                              <option value="" selected>--请选择--</option>
                                          {% for env in  envs %}
                                              <option value="{{env.id}}">{{ env.name }}</option>
                                          {% endfor %}
                                      </select>
                              </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-3 control-label" for="inputSuccess">是否安装Salt </label>
                                <div class="col-xs-8 col-md-6 col-sm-6">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" checked="checked" name="salt"> Saltstack (以下信息用于安装salt客户端,如不安装,不需填写)
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                              <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">SSH 端口 </span></label>
                              <div class="col-xs-8 col-md-6 col-sm-6" >
                                    <input class="form-control" name="port" type="text" value="22">
                              </div>
                            </div>

                            <div class="form-group" >
                              <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">主机用户名 </span></label>
                              <div class="col-xs-8 col-md-6 col-sm-6" >
                                <input class="form-control" name="username" type="text" value="root">
                              </div>
                            </div>

                            <div class="form-group" >
                              <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">用户密码 </span></label>
                              <div class="col-xs-8 col-md-6 col-sm-6" >
                                 <input class="form-control" name="password" type="password" value="{{password}}">
                              </div>
                            </div>
                            <div class="form-group">
                              <div class="col-xs-8 col-md-6 col-sm-6">
                                <button type="button" class="btn" onclick="confirm_to_prod()">提交</button>
                              </div>
                            </div>
                          </form>
                          
                        </div>
                  </section>
              </div>
          </div>
      <!-- page end-->

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script class="include" type="text/javascript" src="{%static 'js/jquery.dcjqaccordion.2.7.js'%}"></script>
    <script src="{%static 'js/jquery.scrollTo.min.js'%}"></script>
    <script src="{%static 'js/jquery.nicescroll.js'%}" type="text/javascript"></script>
    <script src="{%static 'js/respond.min.js'%}" ></script>

    <!--this page plugins-->
    <script type="text/javascript" src="{%static 'assets/fuelux/js/spinner.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-fileupload/bootstrap-fileupload.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-wysihtml5/wysihtml5-0.3.0.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-wysihtml5/bootstrap-wysihtml5.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-datepicker/js/bootstrap-datepicker.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-daterangepicker/moment.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-daterangepicker/daterangepicker.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/bootstrap-timepicker/js/bootstrap-timepicker.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/jquery-multi-select/js/jquery.multi-select.js'%}"></script>
    <script type="text/javascript" src="{%static 'assets/jquery-multi-select/js/jquery.quicksearch.js'%}"></script>
    
    <!--common script for all pages-->
    <script src="{%static 'js/common-scripts.js'%}"></script>
    <script src="{%static 'layer/layer.js'%}"></script>
    
    <!--this page  script only-->
    <script src="{%static 'js/advanced-form-components.js'%}"></script> 
    <script type="text/javascript">
      function confirm_to_prod(){
          document.getElementById("confirm_to_prod").submit();
          layer.msg('请稍等片刻...',function(){
            layer.load(1);
          });
        }
    </script>
  </body>
</html>

installation/templates/installation/ph/server_detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1"  charset="utf-8">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

  </head>

  <body>
        <a href="#" class="list-group-item active" style="background-color: #444f58;">
            <h4 class="list-group-item-heading">
                基本信息
            </h4>
        </a>

        <div class="col-xs-12 col-sm-12">
            <br>
            <ul class="list-group">
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">服务器 ID:</b>{{server.id}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">服务器厂商:</b> {{server.vendor}}</li> 
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">服务器型号:</b> {{server.model}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">PXE IP:</b> {{server.pxe_ip}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">IPMI IP:</b> {{server.ipmi_ip}}</li>
            </ul>
        </div>

        <a href="#" class="list-group-item active" style="background-color: #444f58;">
            <h4 class="list-group-item-heading">
                硬件信息
            </h4>
        </a>

        <br/>
        <div class="col-xs-12 col-sm-12">
            <br>
            <p class="list-group-item-text">
                <h5 class="list-group-item-heading">CPU信息:</h5>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">CPU型号:</b>{{server.cpu_model}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">CPU Sockets:</b> {{server.cpu_sockets}}</li> 
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">CPU Cores:</b> {{server.cpu_cores}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">CPU Threads:</b> {{server.cpu_threads}}</li>
            </p>
        </div>

        <div class="col-xs-12 col-sm-12">
            <br>
            <p class="list-group-item-text">
                <h5 class="list-group-item-heading">内存信息:</h5>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">总内存(G):</b>{{server.mem_size}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">槽位数:</b> {{server.mem_total_slots}}</li> 
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">剩余槽位:</b> {{server.mem_free_slots}}</li>
            </p>          
        </div>



       <div class="col-xs-12 col-sm-12">
          <br>
          <h5 class="list-group-item-heading">硬盘信息:</h5>
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <td>硬盘路径</td>
                    <td>大小</td>
                    <td>类型</td>
                  </tr>
                </thead>
                
                <tbody>
                {% for disk in server.disk_set.all %}
                  <tr>
                    <td>{{disk.path}}</td>
                    <td>{{disk.size}}</td>
                    <td>{{disk.dtype}}</td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>        
       </div>
 
        <!-- </p> -->
 
      <div class="col-xs-12 col-sm-12">
        <br>
        <h5 class="list-group-item-heading">网卡信息:</h5>
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <td>名称</td>
                    <td>MAC</td>
                    <td>型号</td>
                  </tr>
                </thead>
                
                <tbody>
                {% for nic in server.nic_set.all %}
                  <tr>
                    <td>{{nic.name}}</td>
                    <td>{{nic.mac}}</td>
                    <td>{{nic.model}}</td>
                {% endfor %}
                </tbody>
            </table>
       </div>

<!--         <a href="#" class="list-group-item active" style="background-color: #444f58;">
            <h4 class="list-group-item-heading">
                附加信息
                <button onclick="edit_server('{{server.id}}')" class="btn btn-xs">编辑</button>
            </h4>
        </a>

        <div class="col-xs-12 col-sm-12">
            <br>
            <ul class="list-group">
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">机房:</b>
                {% if server.cabinet.idc.name %}
                  {{server.cabinet.idc.name}}
                {% else %}
                  None
                {% endif %}  
                </li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">机柜:</b>
                {% if server.cabinet.name %}
                  {{server.cabinet.name}}
                {% else %}
                  None
                {% endif %} 
                </li> 
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">位置(U):</b> {{server.unit}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">环境:</b>
                {% if server.environment %}
                  {{server.environment.name }}
                {% else %}
                  None
                {% endif %}         
                </li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">联系人:</b>
                {% if server.contacter %}
                  {{server.contacter.name }}
                {% else %}
                  None
                {% endif %}         
                </li>
            </ul>
        </div> -->

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script src="{%static 'layer/layer.js'%}"></script>
<!--     <script type="text/javascript">
            function edit_server(server_id){
              var index = layer.open({
                  type: 2,
                  title: "编辑服务器信息",
                  scrollbar: false,
                  area: ['350px', '350px'],
                  shadeClose: true,
                  shift: 5,
                  moveOut: true,
                  content: ['/installation/server/edit/' + server_id,'no'],
                  end : function(){
                      window.location.reload();
                    }
                });
            }
    </script> -->

  </body>
</html>