opsdb/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^environment/$',views.envs,name='envs'),
    url(r'^environment/add_env/$',views.add_env,name='add_env'),
    url(r'^environment/edit_env/(\d+)/$',views.edit_env,name='edit_env'),
    url(r'^environment/delete/$',views.delete_env,name='delete_env'),
    url(r'^permission_rule/$',views.rules,name='rules'),
    url(r'^permission_rule/edit/(\d+)/$',views.edit_rule,name='edit_rule'),
    url(r'^hosts/$',views.hosts,name='hosts'),
    url(r'^host/(.+)/$',views.host,name='host'),
    url(r'^hosts/search/$',views.search_host,name='search_host'),
    url(r'^hosts/search_exact/$',views.search_exact_host,name='search_exact_host'),
    url(r'^hosts/add/$',views.add_host,name='add_host'),
    url(r'^hosts/add_batch/$',views.add_host_batch,name='add_host_batch'),
    url(r'^hosts/delete/(\d+)/$',views.delete_host,name='delete_host'),
    url(r'^hosts/delete_batch/$',views.delete_host_batch,name='delete_host_batch'),
    url(r'^hosts/edit/(\d+)/$',views.edit_host,name='edit_host'),
    url(r'^hosts/edit_batch/$',views.edit_host_batch,name='edit_host_batch'),
    url(r'^hostgroups/$',views.hostgroups,name='hostgroups'),
    url(r'^hostgroups/add/$',views.add_hostgroup,name='add_hostgroup'),
    url(r'^hostgroups/edit/(\d+)/$',views.edit_hostgroup,name='edit_hostgroup'),
    url(r'^hostgroups/delete/$',views.delete_hostgroup,name='delete_hostgroup'),
    url(r'^ops/cmd/$',views.cmd,name='cmd'),
    url(r'^ops/select_hosts/$',views.select_hosts,name='select_hosts'),
    url(r'^ops/search/$',views.search_host_for_cmd,name='search_host_for_cmd'),
    url(r'^ops/joblist/$',views.joblist,name='joblist'),
    url(r'^ops/job_cjid/(\d+)/$',views.job_cjid,name='job_cjid'),
    url(r'^ops/job_jid/(\d+)/$',views.job_jid,name='job_jid'),
    url(r'^ops/search_job/$',views.search_job,name='search_job'),
    url(r'^ops/cmds/$',views.cmds,name='cmds'),
    url(r'^ops/cmds/black/$',views.black_cmds,name='black_cmds'),
    url(r'^ops/cmds/add/$',views.add_cmd,name='add_cmd'),
    url(r'^ops/cmds/add_black/$',views.add_black_cmd,name='add_black_cmd'),
    url(r'^ops/cmds/edit/(\d+)/$',views.edit_cmd,name='edit_cmd'),
    url(r'^ops/cmds/delete/(\d+)/$',views.delete_cmd,name='delete_cmd'),
    url(r'^ops/cmds/delete/$',views.delete_cmds,name='delete_cmds'),
    url(r'^ops/save_cmd/$',views.save_cmd,name='save_cmd'),
    url(r'^ops/files/get/$',views.get_file,name='get_file'),
    url(r'^ops/files/put/$',views.put_file,name='put_file'),
    url(r'^ops/files/delete/(\d+)/$',views.delete_file,name='delete_file'),
    url(r'^ops/files/push/$',views.push_file,name='push_file'),
    url(r'^ops/scripts/$',views.scripts,name='scripts'),
    url(r'^ops/scripts/upload/$',views.upload_script,name='upload_script'),
    url(r'^ops/scripts/edit/(\d+)/$',views.edit_script,name='edit_script'),
    url(r'^ops/scripts/add/$',views.add_script,name='add_script'),
    url(r'^ops/scripts/copy/(\d+)/$',views.copy_script,name='copy_script'),
    url(r'^ops/scripts/delete/(\d+)/$',views.delete_script,name='delete_script'),
    url(r'^ops/scripts/exacute/(\d+)/$',views.exacute_script,name='exacute_script'),
    url(r'^ops/scripts/search/$',views.search_script,name='search_script'),
    url(r'^ops/states/$',views.states,name='states'),
    url(r'^ops/states/upload/$',views.upload_state,name='upload_state'),
    url(r'^ops/states/deploy/(\d+)/$',views.deploy_state,name='deploy_state'),
    url(r'^ops/states/delete/(\d+)/$',views.delete_state,name='delete_state'),
    url(r'^ops/cron/$',views.cron,name='cron'),
    url(r'^ops/cron/add/$',views.add_cron,name='add_cron'),
    url(r'^ops/cron/delete/(.+)/$',views.delete_cron,name='delete_cron'),
    url(r'^metrics/insert/$',views.metric_to_mongo,name='metric_to_mongo'),
    url(r'^metrics/show_host/(.+)/(.+)/$',views.show_host,name='show_host'),
    url(r'^metrics/show_performance/(.+)/(.+)/$',views.show_performance,name='show_performance'),
    url(r'^metrics/show_user/(.+)/(.+)/$',views.show_user,name='show_user'),
    url(r'^metrics/show_socket/(.+)/(.+)/$',views.show_socket,name='show_socket'),
    url(r'^metrics/show_process/(.+)/(.+)/$',views.show_process,name='show_process'),
    url(r'^zabbix/(.+)/(.+)/$',views.zabbix,name='zabbix'),
    url(r'^zabbix_refresh/$',views.zabbix_refresh,name='zabbix_refresh'),
]

xbox/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
from . import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$',views.base,name="base"),
    url(r'^blank/$',views.blank,name="blank"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),    
	url(r'^accounts/login',views.login,name="login"),
	url(r'^logout/',views.logout,name="logout"),
    url(r'^users/$',views.users,name="users"),
    url(r'^userprofile/(\d+)/$',views.userprofile,name="userprofile"),
    url(r'^changepasswd/$',views.changepasswd,name="changepasswd"),
    url(r'^add_user/$',views.add_user,name='add_user'),
    url(r'^edit_user/(\d+)/$',views.edit_user,name='edit_user'),
    url(r'^disable_user/$',views.disable_user,name='disable_user'),
    url(r'^enable_user/$',views.enable_user,name='enable_user'),
    url(r'^delete_user/$',views.delete_user,name='delete_user'),
    url(r'^reset_password/$',views.resetpwd,name='resetpwd'),
    url(r'^groups/$',views.groups,name='groups'),
    url(r'^group_has_users/(\d+)/$',views.group_has_users,name='group_has_users'),
    url(r'^add_group/$',views.add_group,name='add_group'),
    url(r'^edit_group/(\d+)/$',views.edit_group,name='edit_group'),
    url(r'^delete_group/$',views.delete_group,name='delete_group'),
    url(r'^audit/',include('audit.urls',namespace='audit')),
    url(r'^opsdb/',include('opsdb.urls',namespace='opsdb')),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^installation/', include('installation.urls',namespace='installation')),
]

opsdb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.contrib.auth.models import User,Group
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class Role(models.Model):
	name           = models.CharField(max_length=30, blank=True)
	comment        = models.TextField(max_length=100,blank=True)

	class Meta:
		db_table = 'user_role'

	def __str__(self):
		return self.name

class Profile(models.Model):
	user          = models.OneToOneField(User,related_name='profile', on_delete=models.CASCADE)
	roles         = models.ManyToManyField(Role)
	phone         = models.CharField(max_length=30, blank=True)
	wechat        = models.CharField(max_length=30, blank=True)
	created_by    = models.ForeignKey(User,related_name='created_by',blank=True, null=True,on_delete=models.PROTECT)
	is_delele     = models.BooleanField(default=False)
	comment       = models.TextField(max_length=100,blank=True)

	class Meta:
		db_table = 'user_profile'

	def __str__(self):
		return self.user.username

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)
	instance.profile.save()

class Environment(models.Model):
	name           = models.CharField(max_length=100,blank=True,null=True)
	comment        = models.TextField(max_length=200,blank=True)
	class Meta:
		db_table = 'environment'

	def __unicode__(self):
		return self.name


class Application(models.Model):
	name           = models.CharField(max_length=50,blank=True,null=True)
	comment        = models.TextField(max_length=200,blank=True)

	class Meta:
		db_table = 'application'

	def __unicode__(self):
		return self.name

class HostGroup(models.Model):
	name           = models.CharField(max_length=50,blank=True,null=True)
	comment        = models.TextField(max_length=200,blank=True)

	class Meta:
		db_table = 'hostgroup'

	def __unicode__(self):
		return self.name

class Host(models.Model):
	minion_status_choices =(("O","OK"),("E","Error"),("N","Uninstall"))
	ip            = models.GenericIPAddressField(unique=True)
	hostname      = models.CharField(max_length=100,blank=True,null=True)
	os            = models.CharField(max_length=30,blank=True,null=True)
	is_virtual    = models.CharField(max_length=30,blank=True,null=True)
	minion_id     = models.CharField(max_length=100,unique=True,blank=True,null=True)
	minion_status = models.CharField(max_length=1,choices=minion_status_choices,default="N")
	server_id     = models.CharField(max_length=200,blank=True,null=True,default='server_id')
	comment       = models.CharField(max_length=200,blank=True,null=True)
	hostgroups    = models.ManyToManyField(HostGroup)
	applications  = models.ManyToManyField(Application)
	environment   = models.ForeignKey(Environment,blank=True, null=True,on_delete=models.PROTECT)
	create_time   = models.DateTimeField(auto_now_add=True)
	update_time   = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'host'
		
	def __unicode__(self):
		return self.ip

class Rule(models.Model):
	group         = models.OneToOneField(Group,related_name='rule', on_delete=models.CASCADE)
	hostgroups    = models.ManyToManyField(HostGroup)
	applications  = models.ManyToManyField(Application)
	created_by    = models.ForeignKey(User,blank=True, null=True,on_delete=models.PROTECT)
	comment       = models.TextField(max_length=100,blank=True)

	class Meta:
		db_table = 'permission_rule'

	def __str__(self):
		return self.group.name

@receiver(post_save, sender=Group)
def create_or_update_group_rule(sender, instance, created, **kwargs):
	if created:
		Rule.objects.create(group=instance)
	instance.rule.save()

class Idc(models.Model):
	name               = models.CharField(max_length=100,blank=True,null=True)
	address            = models.CharField(max_length=100,blank=True,null=True)
	comment            = models.TextField(max_length=200,blank=True,default='')

	class Meta:
		db_table = 'idc'

	def __unicode__(self):
		return self.name

class Cabinet(models.Model): 
	sn                 = models.CharField(max_length=100,blank=True,null=True)
	location           = models.CharField(max_length=100,blank=True,null=True)
	size               = models.IntegerField(blank=True,null=True)
	idc                = models.ForeignKey(Idc,blank=True, null=True,on_delete=models.PROTECT)
	comment            = models.TextField(max_length=200,blank=True,default='')
	class Meta:
		db_table = 'cabinet'

	def __unicode__(self):
		return self.sn

class Contacter(models.Model):
	name               = models.CharField(max_length=30,blank=True,null=True)
	phone              = models.CharField(max_length=30,blank=True,null=True)
	email              = models.EmailField(blank=True,null=True)
	dept               = models.CharField(max_length=30,blank=True,null=True)
	company            = models.CharField(max_length=30,blank=True,null=True)

	class Meta:
		db_table = 'contacter'

	def __unicode__(self):
		return self.name

class Cmd(models.Model):
	name               = models.CharField(unique=True,max_length=100)
	argument           = models.CharField(max_length=200,blank=True,null=True)
	created_by         = models.CharField(max_length=80,blank=True,null=True)
	command_type       = models.CharField(max_length=80,default='common')
	create_time        = models.DateTimeField(auto_now_add=True)
	update_time        = models.DateTimeField(auto_now=True)
	comment            = models.CharField(max_length=200,blank=True,null=True)

	class Meta:
		db_table = 'command'

	def __unicode__(self):
		return self.name

class Script(models.Model):
	name               = models.CharField(unique=True,max_length=100)
	script_name        = models.CharField(unique=True,max_length=100)
	created_by         = models.CharField(max_length=80,blank=True,null=True)
	comment            = models.CharField(max_length=200,blank=True,null=True)
	create_time        = models.DateTimeField(auto_now_add=True)
	update_time        = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'script'

	def __unicode__(self):
		return self.name		

class SaltState(models.Model):
	name               = models.CharField(unique=True,max_length=100)
	state_name         = models.CharField(unique=True,max_length=100)
	created_by         = models.CharField(max_length=80,blank=True,null=True)
	comment            = models.CharField(max_length=200,blank=True,null=True)
	create_time        = models.DateTimeField(auto_now_add=True)
	update_time        = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'state'

	def __unicode__(self):
		return self.name

class File(models.Model):
	name               = models.CharField(max_length=100)
	created_by         = models.CharField(max_length=80,blank=True,null=True)
	file_type          = models.CharField(max_length=20,default='upload')
	create_time        = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'file'

	def __unicode__(self):
		return self.name

# class Cron(models.Model):
# 	cron_type_choices  = (("C","command"),("S","script"))
# 	cron_id            = models.CharField(max_length=100)
# 	cron_type          = models.CharField(max_length=1,choices=cron_type_choices,default="C")
# 	cron_string        = models.CharField(max_length=200)
# 	target             = models.TextField()
# 	arg_list           = models.CharField(max_length=200)
# 	create_time        = models.DateTimeField(auto_now_add=True)
# 	create_by          = models.CharField(max_length=200,default="")
# 	description        = models.TextField()

# 	class Meta:
# 		db_table = 'cron'

# 	def __unicode__(self):
# 		return self.cron_id


		

opsdb/templates/opsdb/host/hostgroups.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="{%static 'img/favicon.ico'%}">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-reset.css'%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'assets/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet">
    <link href="{%static 'css/style-responsive.css'%}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{%static 'js/html5shiv.js'%}"></script>
      <script src="{%static 'js/respond.min.js'%}"></script>
    <![endif]-->

  </head>

  <body>

    <section class="wrapper site-min-height">
      <!-- page start-->
      <div class="row">
        <div class="col-lg-12">
            <!--breadcrumbs start -->
            <ul class="breadcrumb">
                <li><a href="#"></i>运维数据库</a></li>
                <li class="active">主机组</li>
            </ul>
            <!--breadcrumbs end -->
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12" id="message">
             {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-block alert-danger fade in">
                            <button data-dismiss="alert" class="close close-sm" type="button">
                                <i class="icon-remove"></i>
                            </button>
                            <strong>Error !</strong> {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-success fade in">
                            <button data-dismiss="alert" class="close close-sm" type="button">
                                <i class="icon-remove"></i>
                            </button>
                            <strong>Success !</strong> {{ message }}
                        </div>
                    {% endif %}                  
                {% endfor %}
              {% endif %}
        </div>
      </div>

      <section class="panel">
        <header class="panel-heading tab-bg-dark-navy-blue ">
            <ul class="nav nav-tabs">
                <li class="">
                    <a href="{%url 'opsdb:hosts'%}" style="left: 15px;">主机</a>
                </li>
                <li class="active">
                    <a href="{%url 'opsdb:hostgroups'%}" style="left: 15px;">主机组</a>
                </li>
            </ul>
        </header> 

        <div class="panel-body">
            <div class="tab-content">
                <div class="tab-pane active">
                      <div class="mail-option">
                             <div class="btn-group">
                                <button type="button" class="btn label label-inverse" onclick="window.location.reload()"><i class="icon-refresh"></i> 刷新</button>
                             </div>
                             <div class="btn-group">
                                 <a href="{% url 'opsdb:add_hostgroup' %}"><button type="button" class="btn label label-inverse"><i class="icon-plus"></i> 添加主机组</button></a>
                             </div>
                             <div class="btn-group">
                                <button type="button" class="btn label label-inverse" onclick="delete_hostgroup()"><i class="icon-trash"></i> 删除主机组</button>
                             </div>

                             <ul class="unstyled inbox-pagination">
                                 <li>
                                  <span class="pages">合计:{{ paginator.count }}&nbsp</span>
                                  <span class="per-page">每页:</span>
                                  <select class="dropdown-select" name="page_number" onchange="javascript:window.location.href='?page_number='+ this.value;">
                                     <option value="{{page_number}}">{{page_number}}</option>
                                     <option value="10">10</option>
                                     <option value="20">20</option>
                                     <option value="50">50</option>
                                     <option value="100">100</option>
                                     <option value="10000">all</option>
                                  </select>
                                 </li>

                                 <li>
                                   <span>&nbsp&nbsp{{ hostgroups.number }} / {{ hostgroups.paginator.num_pages }}</span>
                                 </li>
                                 
                                 <li>
                                     {% if hostgroups.has_previous %}
                                     <a href="?page={{ hostgroups.previous_page_number }}" class="np-btn"><i class="icon-angle-left  pagination-left"></i></a>
                                     {% endif %}
                                 </li>
                                 <li>
                                     {% if hostgroups.has_next %}
                                     <a href="?page={{ hostgroups.next_page_number }}" class="np-btn"><i class="icon-angle-right pagination-right"></i></a>
                                     {% endif %}
                                 </li>
                             </ul>
                      </div>
                      <table class="table table-inbox table-hover" border="5" id='mytable'>
                        <thead>
                                <tr>
                                  <th style="width: 37px;"><input type="checkbox" name="all" id="all"></th>
                                  <th><small>主机组名</small></th>
                                  <th><small>包含主机数</small></th>
                                  <th><small>备注</small></th>
                                  <th><small>操作</small></th>
                                </tr>
                          </thead>
                            <tbody>
                              {% for hostgroup in hostgroups %}
                                <tr>
                                  <td><input type="checkbox"></td>
                                  <td id="{{hostgroup.id}}"><small>{{hostgroup.name}}</small></td>
                                  <td><small><a href="">{{hostgroup.host_set.count}}</a></small></td>
                                  <td><small data-placement="left" data-toggle="tooltip" class="tooltips" data-original-title="{{hostgroup.comment}}">{{hostgroup.comment | truncatewords:5}}</small></td>
                                  <td style="width: 50px;"><small>
                                    <button class="btn btn-primary btn-xs"><a href="{% url 'opsdb:edit_hostgroup' hostgroup.id %}"><i class="icon-pencil"></i></a></button></small></td>
                                </tr>
                              {% endfor %}
                            </tbody>
                      </table>
                    </div>
            </div>
        </div>
      </section>
      <!-- page end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script class="include" type="text/javascript" src="{%static 'js/jquery.dcjqaccordion.2.7.js'%}"></script>
    <script src="{%static 'js/jquery.scrollTo.min.js'%}"></script>
    <script src="{%static 'js/jquery.nicescroll.js'%}" type="text/javascript"></script>
    <script src="{%static 'js/respond.min.js'%}" ></script>

    <!--common script for all pages-->
    <script src="{%static 'js/common-scripts.js'%}"></script>
    <script src="{%static 'layer/layer.js'%}"></script>

    <script type="text/javascript">
        $(function() {
          var all_checked = false;
          $(":checkbox").click(function() {
              var table = $(this).parents("table");
              if($(this).attr("id") === "all") {
                  table.find(":checkbox").prop("checked", !all_checked);
                  all_checked = !all_checked;
              }
              else {
                  table.find(":checkbox[id!=all]").each(function (i) {
                      if(!$(this).is(":checked")) {
                          table.find("#all").prop("checked", false);
                          all_checked = false;
                          return false;
                      }
                      $("#all").prop("checked", true);
                      all_checked = true;
                  });
              }
          });
      });

      function get_server_id(){
        var tbodyObj = document.getElementById('mytable');
        var ids = [];
            $("table :checkbox").each(function(key,value){
                if($(value).prop('checked')){
                    if (value.id == 'all') return true
                    ids.push(tbodyObj.rows[key].cells[1].id);
                }
            });
            return ids
      }

      function delete_hostgroup() {
        var ids = get_server_id();
        if (ids.length == 0 )
        {
          layer.alert("请先选中记录");
        }
        else
        {   
            layer.confirm('请确认是否要删除选中主机组', function(index){
                $.post("{% url 'opsdb:delete_hostgroup' %}",{'ids':ids},function(data){
                    layer.close(index);
                    if (data == 'success')
                    {
                      document.getElementById('message').innerHTML='<div class="alert alert-success fade in"> <button data-dismiss="alert" class="close close-sm" type="button"> <i class="icon-remove"></i> </button> <strong>Success !</strong> 主机组删除成功</div>';
                      setTimeout("window.location.reload()", 2000);
                    }
                    else
                    {
                      document.getElementById('message').innerHTML='<div class="alert alert-block alert-danger fade in"> <button data-dismiss="alert" class="close close-sm" type="button"> <i class="icon-remove"></i> </button> <strong>Error !</strong>' + data + '</div>';
                    }
                  });
            }); 
        }
      }

    </script>
  </body>
</html>

opsdb/templates/opsdb/host/show_performance.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="{%static 'img/favicon.ico'%}">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-reset.css'%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'assets/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet">
    <link href="{%static 'css/style-responsive.css'%}" rel="stylesheet" />
    {% for jsfile_name in script_list %}
    <script src="{{host}}/{{jsfile_name}}.js"></script>
    {% endfor %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{%static 'js/html5shiv.js'%}"></script>
      <script src="{%static 'js/respond.min.js'%}"></script>
    <![endif]-->
  </head>

  <body>

    <section class="wrapper site-min-height">
        <!-- page start-->
        <div class="row">
          <div class="col-lg-12">
              <!--breadcrumbs start -->
              <ul class="breadcrumb">
                  <li><a href="#"></i>运维数据库</a></li>
                  <li><a href="{% url 'opsdb:hosts' %}"></i>主机</a></li>
                  <li class="active">主机信息</li>
              </ul>
              <!--breadcrumbs end -->
          </div>
        </div>

        <section class="panel">
                <header class="panel-heading tab-bg-dark-navy-blue ">
                    <ul class="nav nav-tabs">
                        <li class="">
                            <a href="{% url 'opsdb:show_host' ip hostname %}" style="left: 15px;">概览</a>
                        </li>
                        <li class="active">
                            <a href="{% url 'opsdb:show_performance' ip hostname %}" style="left: 15px;">性能监控</a>
                        </li>
                        <li class="">
                            <a href="{% url 'opsdb:show_user' ip hostname %}" style="left: 15px;">用户信息</a>
                        </li>
                        <li class="">
                            <a href="{% url 'opsdb:show_socket' ip hostname %}" style="left: 15px;">Sockets</a>
                        </li>
                        <li class="">
                            <a href="{% url 'opsdb:show_process' ip hostname %}" style="left: 15px;">Processes</a>
                        </li>
                    </ul>
                </header>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane active">{{myechart|safe}}</div>
                    </div>
                </div>
        </section>
        <!-- page end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script class="include" type="text/javascript" src="{%static 'js/jquery.dcjqaccordion.2.7.js'%}"></script>
    <script src="{%static 'js/jquery.scrollTo.min.js'%}"></script>
    <script src="{%static 'js/jquery.nicescroll.js'%}" type="text/javascript"></script>
    <script src="{%static 'js/respond.min.js'%}" ></script>
    

    <!--common script for all pages-->
    <script src="{%static 'js/common-scripts.js'%}"></script>
    <script src="{%static 'layer/layer.js'%}"></script>
  </body>
</html>